import { FilmHallCellType } from '../../entities';

export const blue = [
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 400, type: FilmHallCellType.COMFORT },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ],
  [
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 0, type: FilmHallCellType.BLOCKED },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY },
    { price: 300, type: FilmHallCellType.ECONOMY }
  ]
];
