pipeline {
    agent any
    
    environment {
        IP = credentials('yandex-apps-ip')
        
        DATABASE_USERNAME = credentials('database-username')
        DATABASE_PASSWORD = credentials('database-password')
        DATABASE_PORT = '27019'
        DATABASE_NAME = 'juniors-bootcamp'
        
        NETWORK_NAME = 'juniors-bootcamp'
        VOLUME_NAME = 'juniors-bootcamp-data'
        CONTAINER_DB_NAME = 'juniors-bootcamp-database'
    }
    
    stages {
        stage('cleanup') {
            steps {
                sh 'docker system prune -a --volumes --force'
            }
        }
        
        stage('deploy database') {
            steps {
                withCredentials(bindings: [sshUserPrivateKey(credentialsId: 'yandex-apps-container', keyFileVariable: 'SSH_PRIVATE_KEY', usernameVariable: 'SSH_USERNAME')]) {
                    sh 'install -m 600 -D /dev/null ~/.ssh/id_rsa'
                    sh 'rm ~/.ssh/id_rsa'
                    sh 'cp -i $SSH_PRIVATE_KEY ~/.ssh/id_rsa'
                    
                    sh 'ssh -o "StrictHostKeyChecking=no" $SSH_USERNAME@$IP \
                        "sudo docker network create $NETWORK_NAME || true"'
                    
                    sh 'ssh -o "StrictHostKeyChecking=no" $SSH_USERNAME@$IP \
                        "sudo docker run --restart=always --name $CONTAINER_DB_NAME -d \
                        -p $DATABASE_PORT:27017 \
                        -e MONGO_INITDB_ROOT_USERNAME=$DATABASE_USERNAME \
                        -e MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD \
                        -v $VOLUME_NAME:/data/db \
                        --network $NETWORK_NAME \
                        mongo:latest || true"'
                }
            }
        }
    }
    
    post {
        always {
            sh 'docker logout'
        }
    }
}
