export * from './film-genre.entity';
export * from './film-hall-cell.entity';
export * from './film-hall.entity';
export * from './film-person.entity';
export * from './film-seance.entity';
export * from './film-shedule.entity';
export * from './film-staff.entity';
export * from './film-user-rating.entity';
export * from './film.entity';
